version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install for a static site."

  build:
    commands:
      - echo "Building static site..."

  post_build:
    commands:
      - echo "Build complete."

artifacts:
  files:
    - '**/*'
  base-directory: './'
