version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo Build started
      - bash -c "mkdir -p dist && shopt -s extglob && cp -r !(dist) dist/"
artifacts:
  files:
    - '**/*'
  base-directory: dist
