version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo Build started
      - mkdir -p dist
      - echo Copying files to dist...
      - cp index.html dist/
artifacts:
  files:
    - '**/*'
  base-directory: dist
