version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo Build started
      - mkdir -p dist
      - cp -r * dist/
artifacts:
  files:
    - '**/*'
  base-directory: dist
